# Generated by Django 4.0 on 2024-03-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0002_branch_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='branch',
            new_name='ifsc',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branch_id',
            new_name='ifsc',
        ),
    ]
