# Generated by Django 4.0 on 2024-03-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0003_rename_branch_account_ifsc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='ifsc',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
