# Generated by Django 4.0 on 2024-03-23 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0004_alter_branch_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_holder_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opened_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
