# Generated by Django 4.0 on 2024-03-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0005_account_account_holder_name_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
