# Generated by Django 4.0 on 2024-03-23 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0007_branch_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='opened_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
