# Generated by Django 4.0 on 2024-03-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0009_alter_profile_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neowave.branch'),
        ),
        migrations.AlterField(
            model_name='account',
            name='ifsc',
            field=models.CharField(default='NEWB0280700', max_length=11),
        ),
    ]
