# Generated by Django 4.0 on 2024-03-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0010_account_branch_name_alter_account_ifsc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_id',
        ),
    ]
