# Generated by Django 4.0 on 2024-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0011_remove_branch_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ifsc',
            field=models.CharField(default='', max_length=11),
        ),
    ]
