# Generated by Django 4.0 on 2024-03-24 08:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('neowave', '0012_alter_account_ifsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='opened_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_account_number', models.CharField(max_length=12)),
                ('receiver_ifsc', models.CharField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_reference_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='auth.user')),
            ],
        ),
    ]
