# Generated by Django 4.0 on 2024-03-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0013_alter_account_opened_date_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='neowave.account'),
        ),
    ]
