# Generated by Django 4.0 on 2024-03-24 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0014_remove_transaction_sender_transaction_sender_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='neowave.account'),
        ),
    ]
