# Generated by Django 4.0 on 2024-03-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0015_alter_transaction_sender_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
