# Generated by Django 4.0 on 2024-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0016_transaction_beneficiary_name_transaction_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_balance_after_transaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_balance_after_transaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
