# Generated by Django 4.0 on 2024-04-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0018_cheque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='issuer',
        ),
    ]
