# Generated by Django 4.0 on 2024-04-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neowave', '0019_remove_cheque_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='stop_reason',
            field=models.CharField(blank=True, choices=[('lost', 'Cheque Reported Lost'), ('stopped', 'Payment Stopped by Drawer')], max_length=10, null=True),
        ),
    ]
